class Event:
    """this is a superclass for any events that might be generated by an
    object and sent to the EventManager"""
    def __init__(self):
        self.name = "Generic Event"

class KeyPressEvent(Event):
    def __init__(self, key):
        self.name = "Keypress Event"
        self.key = key

class MouseClickEvent(Event):
    def __init__(self, button, pos):
        self.name = "Mouse Click Event"
        self.button = button
        self.pos = pos
